nodes:
  - 
    id: 0
  -
    id: 1
  - 
    id: 2
  - 
    id: 3
  - 
    id: 4
  - 
    id: 5
  -
    id: 6
roads:
  -
    begin: 0
    end: 1
  - 
    begin: 0
    end: 2
  - 
    begin: 0
    end: 6
  - 
    begin: 1
    end: 3
  -
    begin: 1
    end: 5
  - 
    begin: 2
    end: 4
  -
    begin: 2
    end: 6
  - 
    begin: 3
    end: 5
  - 
    begin: 4
    end: 6
  -
    begin: 6
    end: 5